### ISSUE TITLE
Add remaining Nomisma fields

### ISSUE THREAD

**Issue by kmcelwee** [pulibrary/nomisma#28]
[nomisma.org: Ontology](http://nomisma.org/ontology)
- [x] ObjectType: coin
- [ ] [nmo:TypeSeriesItem](http://nomisma.org/ontology#TypeSeriesItem) (See #32)
- [x] [nmo:hasAxis](http://nomisma.org/ontology#hasAxis) 
~- [ ] [nmo:hasBearsDate](http://nomisma.org/ontology#hasBearsDate)~
~- [ ] [nmo:hasDate](http://nomisma.org/ontology#hasDate)~
- [x] [nmo:hasDiameter](http://nomisma.org/ontology#hasDiameter) 
- [ ] [nmo:hasStartDate](http://nomisma.org/ontology#hasStartDate) (See #31)
- [ ] [nmo:hasEndDate](http://nomisma.org/ontology#hasEndDate) (See #31)
- [ ] [nmo:hasManufacture](http://nomisma.org/ontology#hasManufacture) (See #33)
- [x] [nmo:hasMaterial](http://nomisma.org/ontology#hasMaterial) 
~- [ ] [nmo:hasMint](http://nomisma.org/ontology#hasMint)~ 
- [ ] [nmo:hasFindspot](http://nomisma.org/ontology#hasFindspot) (See #30)
~- [ ] [nmo:hasObjectType](http://nomisma.org/ontology#hasObjectType) ~
- [ ] Add IIIF

**Comment by kmcelwee** [comment]
and #4

**Comment by kmcelwee** [comment]
- [ ] Are medals considered coins?
